// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ElmResourceCreateController from "./elm_resource_create_controller"
application.register("elm-resource-create", ElmResourceCreateController)
