// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BooleanAsButtonController from "./boolean_as_button_controller"
application.register("boolean-as-button", BooleanAsButtonController)

import ButtonTogglerController from "./button_toggler_controller"
application.register("button-toggler", ButtonTogglerController)

import CopperToPgscController from "./copper_to_pgsc_controller"
application.register("copper-to-pgsc", CopperToPgscController)

import DynamicStatsController from "./dynamic_stats_controller"
application.register("dynamic-stats", DynamicStatsController)

import ElmMapsShowController from "./elm_maps_show_controller"
application.register("elm-maps-show", ElmMapsShowController)

import ItemClassSetterController from "./item_class_setter_controller"
application.register("item-class-setter", ItemClassSetterController)

import JumplocParserController from "./jumploc_parser_controller"
application.register("jumploc-parser", JumplocParserController)

import LocationFilterController from "./location_filter_controller"
application.register("location-filter", LocationFilterController)

import RealtimeSearchController from "./realtime_search_controller"
application.register("realtime-search", RealtimeSearchController)
