// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BooleanAsButtonController from "./boolean_as_button_controller"
application.register("boolean-as-button", BooleanAsButtonController)

import ButtonTogglerController from "./button_toggler_controller"
application.register("button-toggler", ButtonTogglerController)

import CopperToPgscController from "./copper_to_pgsc_controller"
application.register("copper-to-pgsc", CopperToPgscController)

import DynamicStatsController from "./dynamic_stats_controller"
application.register("dynamic-stats", DynamicStatsController)

import ElmItemCreateController from "./elm_item_create_controller"
application.register("elm-item-create", ElmItemCreateController)

import ElmMapsShowController from "./elm_maps_show_controller"
application.register("elm-maps-show", ElmMapsShowController)

import ElmResourceCreateController from "./elm_resource_create_controller"
application.register("elm-resource-create", ElmResourceCreateController)

import JumplocParserController from "./jumploc_parser_controller"
application.register("jumploc-parser", JumplocParserController)

import RealtimeSearchController from "./realtime_search_controller"
application.register("realtime-search", RealtimeSearchController)

import TurboLoaderController from "./turbo_loader_controller"
application.register("turbo-loader", TurboLoaderController)
