version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=pantheon
      - POSTGRES_USER=pantheon
      - POSTGRES_PASSWORD=pantheon
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    volumes:
      - .:/rails
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=pantheon
      - POSTGRES_USER=pantheon
      - POSTGRES_PASSWORD=pantheon
      - RAILS_ENV=development
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

volumes:
  postgres-data:
