version: "3.8"

x-app: &app
  build:
    context: .
  volumes:
    - .env:/rails/.env:ro

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=pantheon
      - POSTGRES_USER=pantheon
      - POSTGRES_PASSWORD=pantheon
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    <<: *app
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=pantheon
      - POSTGRES_USER=pantheon
      - POSTGRES_PASSWORD=pantheon
      - RAILS_ENV=production
      - SECRET_KEY_BASE=foo
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

volumes:
  postgres-data:
  assets:
