version: "3.8"

x-app: &app
  volumes:
    - .:/rails:delegated
    - /rails/node_modules
    - /rails/elm-stuff
  environment:
    - SECRET_KEY_BASE
  build:
    context: .

services:
  watch-js:
    <<: *app
    command: yarn run build:watch
  watch-css:
    <<: *app
    command: yarn run build:css:watch

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=pantheon
      - POSTGRES_USER=pantheon
      - POSTGRES_PASSWORD=pantheon
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    <<: *app
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=pantheon
      - POSTGRES_USER=pantheon
      - POSTGRES_PASSWORD=pantheon
      - RAILS_ENV=development
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

volumes:
  postgres-data:
  assets:
