# frozen_string_literal: true

source 'https://rubygems.org'

gem 'administrate'
gem 'administrate-field-jsonb'
gem 'ar_lazy_preload'
gem 'blueprinter'
gem 'cancancan'
gem 'cssbundling-rails'
gem 'discard'
gem 'dotenv'
gem 'graphiql-rails'
gem 'redis'
gem 'graphql'
gem 'graphql-fragment_cache'
gem 'iodine'
gem 'jsbundling-rails'
gem 'marcel'
gem 'nokogiri'
gem 'oauth2'
gem 'paper_trail'
gem 'pg'
gem 'rack-cors'
gem 'rails'
gem 'rubocop'
gem 'sentry-rails'
gem 'stimulus-rails'
