-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.Item exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.Enum.Class
import PantheonApi.Enum.ItemAttr
import PantheonApi.Enum.ItemCategory
import PantheonApi.Enum.ItemSlot
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


{-| An array of attributes on the item.
-}
attrs : SelectionSet (List PantheonApi.Enum.ItemAttr.ItemAttr) PantheonApi.Object.Item
attrs =
    Object.selectionForField "(List Enum.ItemAttr.ItemAttr)" "attrs" [] (PantheonApi.Enum.ItemAttr.decoder |> Decode.list)


buyPrice : SelectionSet (Maybe Int) PantheonApi.Object.Item
buyPrice =
    Object.selectionForField "(Maybe Int)" "buyPrice" [] (Decode.int |> Decode.nullable)


category : SelectionSet (Maybe PantheonApi.Enum.ItemCategory.ItemCategory) PantheonApi.Object.Item
category =
    Object.selectionForField "(Maybe Enum.ItemCategory.ItemCategory)" "category" [] (PantheonApi.Enum.ItemCategory.decoder |> Decode.nullable)


{-| An array of classes that can use the item.
-}
classes : SelectionSet (List PantheonApi.Enum.Class.Class) PantheonApi.Object.Item
classes =
    Object.selectionForField "(List Enum.Class.Class)" "classes" [] (PantheonApi.Enum.Class.decoder |> Decode.list)


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Item
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


droppedBy :
    SelectionSet decodesTo PantheonApi.Object.Monster
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Item
droppedBy object____ =
    Object.selectionForCompositeField "droppedBy" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.Item
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String PantheonApi.Object.Item
name =
    Object.selectionForField "String" "name" [] Decode.string


patch :
    SelectionSet decodesTo PantheonApi.Object.Patch
    -> SelectionSet decodesTo PantheonApi.Object.Item
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


requiredLevel : SelectionSet (Maybe Int) PantheonApi.Object.Item
requiredLevel =
    Object.selectionForField "(Maybe Int)" "requiredLevel" [] (Decode.int |> Decode.nullable)


rewardedFromQuests :
    SelectionSet decodesTo PantheonApi.Object.Quest
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Item
rewardedFromQuests object____ =
    Object.selectionForCompositeField "rewardedFromQuests" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


sellPrice : SelectionSet (Maybe Int) PantheonApi.Object.Item
sellPrice =
    Object.selectionForField "(Maybe Int)" "sellPrice" [] (Decode.int |> Decode.nullable)


slot : SelectionSet (Maybe PantheonApi.Enum.ItemSlot.ItemSlot) PantheonApi.Object.Item
slot =
    Object.selectionForField "(Maybe Enum.ItemSlot.ItemSlot)" "slot" [] (PantheonApi.Enum.ItemSlot.decoder |> Decode.nullable)


startsQuest :
    SelectionSet decodesTo PantheonApi.Object.Quest
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.Item
startsQuest object____ =
    Object.selectionForCompositeField "startsQuest" [] object____ (Basics.identity >> Decode.nullable)


stats :
    SelectionSet decodesTo PantheonApi.Object.ItemStats
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.Item
stats object____ =
    Object.selectionForCompositeField "stats" [] object____ (Basics.identity >> Decode.nullable)


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Item
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


weight : SelectionSet Float PantheonApi.Object.Item
weight =
    Object.selectionForField "Float" "weight" [] Decode.float
