-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.ItemStats exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


agility : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
agility =
    Object.selectionForField "(Maybe Int)" "agility" [] (Decode.int |> Decode.nullable)


armor : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
armor =
    Object.selectionForField "(Maybe Int)" "armor" [] (Decode.int |> Decode.nullable)


attackPower : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
attackPower =
    Object.selectionForField "(Maybe Int)" "attackPower" [] (Decode.int |> Decode.nullable)


blockRating : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
blockRating =
    Object.selectionForField "(Maybe Int)" "blockRating" [] (Decode.int |> Decode.nullable)


charisma : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
charisma =
    Object.selectionForField "(Maybe Int)" "charisma" [] (Decode.int |> Decode.nullable)


chemicalResist : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
chemicalResist =
    Object.selectionForField "(Maybe Int)" "chemicalResist" [] (Decode.int |> Decode.nullable)


coldResist : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
coldResist =
    Object.selectionForField "(Maybe Int)" "coldResist" [] (Decode.int |> Decode.nullable)


constitution : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
constitution =
    Object.selectionForField "(Maybe Int)" "constitution" [] (Decode.int |> Decode.nullable)


damage : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
damage =
    Object.selectionForField "(Maybe Int)" "damage" [] (Decode.int |> Decode.nullable)


delay : SelectionSet (Maybe Float) PantheonApi.Object.ItemStats
delay =
    Object.selectionForField "(Maybe Float)" "delay" [] (Decode.float |> Decode.nullable)


dexterity : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
dexterity =
    Object.selectionForField "(Maybe Int)" "dexterity" [] (Decode.int |> Decode.nullable)


dodge : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
dodge =
    Object.selectionForField "(Maybe Int)" "dodge" [] (Decode.int |> Decode.nullable)


endurance : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
endurance =
    Object.selectionForField "(Maybe Int)" "endurance" [] (Decode.int |> Decode.nullable)


fireResist : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
fireResist =
    Object.selectionForField "(Maybe Int)" "fireResist" [] (Decode.int |> Decode.nullable)


health : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
health =
    Object.selectionForField "(Maybe Int)" "health" [] (Decode.int |> Decode.nullable)


healthRecoveryWhileResting : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
healthRecoveryWhileResting =
    Object.selectionForField "(Maybe Int)" "healthRecoveryWhileResting" [] (Decode.int |> Decode.nullable)


hitRating : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
hitRating =
    Object.selectionForField "(Maybe Int)" "hitRating" [] (Decode.int |> Decode.nullable)


intellect : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
intellect =
    Object.selectionForField "(Maybe Int)" "intellect" [] (Decode.int |> Decode.nullable)


magicResist : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
magicResist =
    Object.selectionForField "(Maybe Int)" "magicResist" [] (Decode.int |> Decode.nullable)


mana : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
mana =
    Object.selectionForField "(Maybe Int)" "mana" [] (Decode.int |> Decode.nullable)


manaRecoveryWhileResting : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
manaRecoveryWhileResting =
    Object.selectionForField "(Maybe Int)" "manaRecoveryWhileResting" [] (Decode.int |> Decode.nullable)


natureResist : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
natureResist =
    Object.selectionForField "(Maybe Int)" "natureResist" [] (Decode.int |> Decode.nullable)


parry : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
parry =
    Object.selectionForField "(Maybe Int)" "parry" [] (Decode.int |> Decode.nullable)


poisonResist : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
poisonResist =
    Object.selectionForField "(Maybe Int)" "poisonResist" [] (Decode.int |> Decode.nullable)


spellCritChance : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
spellCritChance =
    Object.selectionForField "(Maybe Int)" "spellCritChance" [] (Decode.int |> Decode.nullable)


spellPower : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
spellPower =
    Object.selectionForField "(Maybe Int)" "spellPower" [] (Decode.int |> Decode.nullable)


stamina : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
stamina =
    Object.selectionForField "(Maybe Int)" "stamina" [] (Decode.int |> Decode.nullable)


strength : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
strength =
    Object.selectionForField "(Maybe Int)" "strength" [] (Decode.int |> Decode.nullable)


wisdom : SelectionSet (Maybe Int) PantheonApi.Object.ItemStats
wisdom =
    Object.selectionForField "(Maybe Int)" "wisdom" [] (Decode.int |> Decode.nullable)
