-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.Location exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Location
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


dungeon :
    SelectionSet decodesTo PantheonApi.Object.Dungeon
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.Location
dungeon object____ =
    Object.selectionForCompositeField "dungeon" [] object____ (Basics.identity >> Decode.nullable)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.Location
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


monsters :
    SelectionSet decodesTo PantheonApi.Object.Monster
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Location
monsters object____ =
    Object.selectionForCompositeField "monsters" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


name : SelectionSet String PantheonApi.Object.Location
name =
    Object.selectionForField "String" "name" [] Decode.string


npcs :
    SelectionSet decodesTo PantheonApi.Object.Npc
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Location
npcs object____ =
    Object.selectionForCompositeField "npcs" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


settlement :
    SelectionSet decodesTo PantheonApi.Object.Settlement
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.Location
settlement object____ =
    Object.selectionForCompositeField "settlement" [] object____ (Basics.identity >> Decode.nullable)


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Location
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


zone :
    SelectionSet decodesTo PantheonApi.Object.Zone
    -> SelectionSet decodesTo PantheonApi.Object.Location
zone object____ =
    Object.selectionForCompositeField "zone" [] object____ Basics.identity
