-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.Monster exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Monster
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


drops :
    SelectionSet decodesTo PantheonApi.Object.Item
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Monster
drops object____ =
    Object.selectionForCompositeField "drops" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


elite : SelectionSet Bool PantheonApi.Object.Monster
elite =
    Object.selectionForField "Bool" "elite" [] Decode.bool


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.Monster
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


level : SelectionSet Int PantheonApi.Object.Monster
level =
    Object.selectionForField "Int" "level" [] Decode.int


locX : SelectionSet (Maybe Float) PantheonApi.Object.Monster
locX =
    Object.selectionForField "(Maybe Float)" "locX" [] (Decode.float |> Decode.nullable)


locY : SelectionSet (Maybe Float) PantheonApi.Object.Monster
locY =
    Object.selectionForField "(Maybe Float)" "locY" [] (Decode.float |> Decode.nullable)


locZ : SelectionSet (Maybe Float) PantheonApi.Object.Monster
locZ =
    Object.selectionForField "(Maybe Float)" "locZ" [] (Decode.float |> Decode.nullable)


location :
    SelectionSet decodesTo PantheonApi.Object.Location
    -> SelectionSet decodesTo PantheonApi.Object.Monster
location object____ =
    Object.selectionForCompositeField "location" [] object____ Basics.identity


name : SelectionSet String PantheonApi.Object.Monster
name =
    Object.selectionForField "String" "name" [] Decode.string


named : SelectionSet Bool PantheonApi.Object.Monster
named =
    Object.selectionForField "Bool" "named" [] Decode.bool


patch :
    SelectionSet decodesTo PantheonApi.Object.Patch
    -> SelectionSet decodesTo PantheonApi.Object.Monster
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Monster
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


{-| Shortcut for location -> zone. May be removed.
-}
zone :
    SelectionSet decodesTo PantheonApi.Object.Zone
    -> SelectionSet decodesTo PantheonApi.Object.Monster
zone object____ =
    Object.selectionForCompositeField "zone" [] object____ Basics.identity
