-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.Npc exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Npc
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.Npc
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


locX : SelectionSet (Maybe Float) PantheonApi.Object.Npc
locX =
    Object.selectionForField "(Maybe Float)" "locX" [] (Decode.float |> Decode.nullable)


locY : SelectionSet (Maybe Float) PantheonApi.Object.Npc
locY =
    Object.selectionForField "(Maybe Float)" "locY" [] (Decode.float |> Decode.nullable)


locZ : SelectionSet (Maybe Float) PantheonApi.Object.Npc
locZ =
    Object.selectionForField "(Maybe Float)" "locZ" [] (Decode.float |> Decode.nullable)


location :
    SelectionSet decodesTo PantheonApi.Object.Location
    -> SelectionSet decodesTo PantheonApi.Object.Npc
location object____ =
    Object.selectionForCompositeField "location" [] object____ Basics.identity


name : SelectionSet String PantheonApi.Object.Npc
name =
    Object.selectionForField "String" "name" [] Decode.string


patch :
    SelectionSet decodesTo PantheonApi.Object.Patch
    -> SelectionSet decodesTo PantheonApi.Object.Npc
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


questsGiven :
    SelectionSet decodesTo PantheonApi.Object.Quest
    -> SelectionSet (List decodesTo) PantheonApi.Object.Npc
questsGiven object____ =
    Object.selectionForCompositeField "questsGiven" [] object____ (Basics.identity >> Decode.list)


questsReceived :
    SelectionSet decodesTo PantheonApi.Object.Quest
    -> SelectionSet (List decodesTo) PantheonApi.Object.Npc
questsReceived object____ =
    Object.selectionForCompositeField "questsReceived" [] object____ (Basics.identity >> Decode.list)


sellsItems :
    SelectionSet decodesTo PantheonApi.Object.Item
    -> SelectionSet (List decodesTo) PantheonApi.Object.Npc
sellsItems object____ =
    Object.selectionForCompositeField "sellsItems" [] object____ (Basics.identity >> Decode.list)


subtitle : SelectionSet (Maybe String) PantheonApi.Object.Npc
subtitle =
    Object.selectionForField "(Maybe String)" "subtitle" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Npc
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


vendor : SelectionSet Bool PantheonApi.Object.Npc
vendor =
    Object.selectionForField "Bool" "vendor" [] Decode.bool


{-| Shortcut for location -> zone. May be removed.
-}
zone :
    SelectionSet decodesTo PantheonApi.Object.Zone
    -> SelectionSet decodesTo PantheonApi.Object.Npc
zone object____ =
    Object.selectionForCompositeField "zone" [] object____ Basics.identity
