-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.Patch exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Patch
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.Patch
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Patch
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


version : SelectionSet String PantheonApi.Object.Patch
version =
    Object.selectionForField "String" "version" [] Decode.string
