-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.Quest exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Quest
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


{-| Item that starts this Quest
-}
droppedAs :
    SelectionSet decodesTo PantheonApi.Object.Item
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.Quest
droppedAs object____ =
    Object.selectionForCompositeField "droppedAs" [] object____ (Basics.identity >> Decode.nullable)


{-| Npc that starts this Quest
-}
giver :
    SelectionSet decodesTo PantheonApi.Object.Npc
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.Quest
giver object____ =
    Object.selectionForCompositeField "giver" [] object____ (Basics.identity >> Decode.nullable)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.Quest
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String PantheonApi.Object.Quest
name =
    Object.selectionForField "String" "name" [] Decode.string


patch :
    SelectionSet decodesTo PantheonApi.Object.Patch
    -> SelectionSet decodesTo PantheonApi.Object.Quest
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


{-| Quest that must be complete before this one is available
-}
prereqQuest :
    SelectionSet decodesTo PantheonApi.Object.Quest
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.Quest
prereqQuest object____ =
    Object.selectionForCompositeField "prereqQuest" [] object____ (Basics.identity >> Decode.nullable)


questObjectives :
    SelectionSet decodesTo PantheonApi.Object.QuestObjective
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Quest
questObjectives object____ =
    Object.selectionForCompositeField "questObjectives" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


questRewards :
    SelectionSet decodesTo PantheonApi.Object.QuestReward
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Quest
questRewards object____ =
    Object.selectionForCompositeField "questRewards" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| Npc that completes this Quest
-}
receiver :
    SelectionSet decodesTo PantheonApi.Object.Npc
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.Quest
receiver object____ =
    Object.selectionForCompositeField "receiver" [] object____ (Basics.identity >> Decode.nullable)


{-| Quests that open after this one is complete
-}
successiveQuests :
    SelectionSet decodesTo PantheonApi.Object.Quest
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Quest
successiveQuests object____ =
    Object.selectionForCompositeField "successiveQuests" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


text : SelectionSet String PantheonApi.Object.Quest
text =
    Object.selectionForField "String" "text" [] Decode.string


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Quest
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)
