-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.QuestReward exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


amount : SelectionSet (Maybe Float) PantheonApi.Object.QuestReward
amount =
    Object.selectionForField "(Maybe Float)" "amount" [] (Decode.float |> Decode.nullable)


copper : SelectionSet (Maybe Bool) PantheonApi.Object.QuestReward
copper =
    Object.selectionForField "(Maybe Bool)" "copper" [] (Decode.bool |> Decode.nullable)


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.QuestReward
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.QuestReward
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


item :
    SelectionSet decodesTo PantheonApi.Object.Item
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.QuestReward
item object____ =
    Object.selectionForCompositeField "item" [] object____ (Basics.identity >> Decode.nullable)


patch :
    SelectionSet decodesTo PantheonApi.Object.Patch
    -> SelectionSet decodesTo PantheonApi.Object.QuestReward
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


quest :
    SelectionSet decodesTo PantheonApi.Object.Quest
    -> SelectionSet decodesTo PantheonApi.Object.QuestReward
quest object____ =
    Object.selectionForCompositeField "quest" [] object____ Basics.identity


{-| A dynamically generated field that attempts to summarise the reward based on all the other fields, so for example if copper is true, and amount is 50, this will return "50 Copper"

This is mostly for convenience and is very rudimentary!

-}
readable : SelectionSet (Maybe String) PantheonApi.Object.QuestReward
readable =
    Object.selectionForField "(Maybe String)" "readable" [] (Decode.string |> Decode.nullable)


skill : SelectionSet (Maybe String) PantheonApi.Object.QuestReward
skill =
    Object.selectionForField "(Maybe String)" "skill" [] (Decode.string |> Decode.nullable)


standing : SelectionSet (Maybe Bool) PantheonApi.Object.QuestReward
standing =
    Object.selectionForField "(Maybe Bool)" "standing" [] (Decode.bool |> Decode.nullable)


text : SelectionSet (Maybe String) PantheonApi.Object.QuestReward
text =
    Object.selectionForField "(Maybe String)" "text" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.QuestReward
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


xp : SelectionSet (Maybe Bool) PantheonApi.Object.QuestReward
xp =
    Object.selectionForField "(Maybe Bool)" "xp" [] (Decode.bool |> Decode.nullable)
