-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.QuestObjective exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


amount : SelectionSet (Maybe Int) PantheonApi.Object.QuestObjective
amount =
    Object.selectionForField "(Maybe Int)" "amount" [] (Decode.int |> Decode.nullable)


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.QuestObjective
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.QuestObjective
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


item :
    SelectionSet decodesTo PantheonApi.Object.Item
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.QuestObjective
item object____ =
    Object.selectionForCompositeField "item" [] object____ (Basics.identity >> Decode.nullable)


monster :
    SelectionSet decodesTo PantheonApi.Object.Monster
    -> SelectionSet (Maybe decodesTo) PantheonApi.Object.QuestObjective
monster object____ =
    Object.selectionForCompositeField "monster" [] object____ (Basics.identity >> Decode.nullable)


patch :
    SelectionSet decodesTo PantheonApi.Object.Patch
    -> SelectionSet decodesTo PantheonApi.Object.QuestObjective
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


quest :
    SelectionSet decodesTo PantheonApi.Object.Quest
    -> SelectionSet decodesTo PantheonApi.Object.QuestObjective
quest object____ =
    Object.selectionForCompositeField "quest" [] object____ Basics.identity


{-| A dynamically generated field that attempts to summarise the objective based on all the other fields, so for example if item is set, and amount is 10, this may return "10 Wolf Pelt"

This is mostly for convenience and is very rudimentary!

-}
readable : SelectionSet (Maybe String) PantheonApi.Object.QuestObjective
readable =
    Object.selectionForField "(Maybe String)" "readable" [] (Decode.string |> Decode.nullable)


text : SelectionSet String PantheonApi.Object.QuestObjective
text =
    Object.selectionForField "String" "text" [] Decode.string


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.QuestObjective
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)
