-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.Resource exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.Enum.ResourceResource
import PantheonApi.Enum.ResourceSize
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Resource
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.Resource
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


locX : SelectionSet Float PantheonApi.Object.Resource
locX =
    Object.selectionForField "Float" "locX" [] Decode.float


locY : SelectionSet Float PantheonApi.Object.Resource
locY =
    Object.selectionForField "Float" "locY" [] Decode.float


locZ : SelectionSet Float PantheonApi.Object.Resource
locZ =
    Object.selectionForField "Float" "locZ" [] Decode.float


name : SelectionSet String PantheonApi.Object.Resource
name =
    Object.selectionForField "String" "name" [] Decode.string


patch :
    SelectionSet decodesTo PantheonApi.Object.Patch
    -> SelectionSet decodesTo PantheonApi.Object.Resource
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


resource : SelectionSet PantheonApi.Enum.ResourceResource.ResourceResource PantheonApi.Object.Resource
resource =
    Object.selectionForField "Enum.ResourceResource.ResourceResource" "resource" [] PantheonApi.Enum.ResourceResource.decoder


size : SelectionSet PantheonApi.Enum.ResourceSize.ResourceSize PantheonApi.Object.Resource
size =
    Object.selectionForField "Enum.ResourceSize.ResourceSize" "size" [] PantheonApi.Enum.ResourceSize.decoder


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Resource
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)
