-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.Settlement exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Settlement
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.Settlement
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


locations :
    SelectionSet decodesTo PantheonApi.Object.Location
    -> SelectionSet (List decodesTo) PantheonApi.Object.Settlement
locations object____ =
    Object.selectionForCompositeField "locations" [] object____ (Basics.identity >> Decode.list)


{-| Shortcut for locations -> monsters.

An array of Monsters that can be found in this Settlement.

-}
monsters :
    SelectionSet decodesTo PantheonApi.Object.Monster
    -> SelectionSet (List decodesTo) PantheonApi.Object.Settlement
monsters object____ =
    Object.selectionForCompositeField "monsters" [] object____ (Basics.identity >> Decode.list)


name : SelectionSet String PantheonApi.Object.Settlement
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| Shortcut for locations -> npcs.

An array of Npcs that can be found in this Settlement.

-}
npcs :
    SelectionSet decodesTo PantheonApi.Object.Npc
    -> SelectionSet (List decodesTo) PantheonApi.Object.Settlement
npcs object____ =
    Object.selectionForCompositeField "npcs" [] object____ (Basics.identity >> Decode.list)


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Settlement
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)
