-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.Object.Zone exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PantheonApi.InputObject
import PantheonApi.Interface
import PantheonApi.Object
import PantheonApi.Scalar
import PantheonApi.ScalarCodecs
import PantheonApi.Union


createdAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Zone
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


id : SelectionSet PantheonApi.ScalarCodecs.Id PantheonApi.Object.Zone
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


locations :
    SelectionSet decodesTo PantheonApi.Object.Location
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Zone
locations object____ =
    Object.selectionForCompositeField "locations" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| Shortcut for locations -> monsters
-}
monsters :
    SelectionSet decodesTo PantheonApi.Object.Monster
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Zone
monsters object____ =
    Object.selectionForCompositeField "monsters" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


name : SelectionSet String PantheonApi.Object.Zone
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| Shortcut for locations -> npcs
-}
npcs :
    SelectionSet decodesTo PantheonApi.Object.Npc
    -> SelectionSet (Maybe (List decodesTo)) PantheonApi.Object.Zone
npcs object____ =
    Object.selectionForCompositeField "npcs" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


patch :
    SelectionSet decodesTo PantheonApi.Object.Patch
    -> SelectionSet decodesTo PantheonApi.Object.Zone
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


updatedAt : SelectionSet PantheonApi.ScalarCodecs.ISO8601DateTime PantheonApi.Object.Zone
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (PantheonApi.ScalarCodecs.codecs |> PantheonApi.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)
