-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias AssignDroppedItemToMonsterRequiredArguments =
    { monsterId : Api.ScalarCodecs.Id
    , itemId : Api.ScalarCodecs.Id
    }


{-| Add an item to a monster's drop table

  - monsterId - ID of Monster to add to
  - itemId - Item ID to add

-}
assignDroppedItemToMonster :
    AssignDroppedItemToMonsterRequiredArguments
    -> SelectionSet decodesTo Api.Object.SuccessResult
    -> SelectionSet (Maybe decodesTo) RootMutation
assignDroppedItemToMonster requiredArgs____ object____ =
    Object.selectionForCompositeField "assignDroppedItemToMonster" [ Argument.required "monsterId" requiredArgs____.monsterId (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "itemId" requiredArgs____.itemId (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias AssignSoldItemToNpcRequiredArguments =
    { npcId : Api.ScalarCodecs.Id
    , itemId : Api.ScalarCodecs.Id
    }


{-| Add an item to an NPC's vendor sell list

  - npcId - ID of NPC to add to
  - itemId - Item ID to add

-}
assignSoldItemToNpc :
    AssignSoldItemToNpcRequiredArguments
    -> SelectionSet decodesTo Api.Object.SuccessResult
    -> SelectionSet (Maybe decodesTo) RootMutation
assignSoldItemToNpc requiredArgs____ object____ =
    Object.selectionForCompositeField "assignSoldItemToNpc" [ Argument.required "npcId" requiredArgs____.npcId (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "itemId" requiredArgs____.itemId (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias CreateItemRequiredArguments =
    { attributes : Api.InputObject.ItemAttributes }


createItem :
    CreateItemRequiredArguments
    -> SelectionSet decodesTo Api.Object.ItemResult
    -> SelectionSet (Maybe decodesTo) RootMutation
createItem requiredArgs____ object____ =
    Object.selectionForCompositeField "createItem" [ Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeItemAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias CreateMonsterRequiredArguments =
    { attributes : Api.InputObject.MonsterAttributes }


createMonster :
    CreateMonsterRequiredArguments
    -> SelectionSet decodesTo Api.Object.MonsterResult
    -> SelectionSet (Maybe decodesTo) RootMutation
createMonster requiredArgs____ object____ =
    Object.selectionForCompositeField "createMonster" [ Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeMonsterAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias CreateNpcRequiredArguments =
    { attributes : Api.InputObject.NpcAttributes }


createNpc :
    CreateNpcRequiredArguments
    -> SelectionSet decodesTo Api.Object.NpcResult
    -> SelectionSet (Maybe decodesTo) RootMutation
createNpc requiredArgs____ object____ =
    Object.selectionForCompositeField "createNpc" [ Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeNpcAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias CreateQuestRequiredArguments =
    { attributes : Api.InputObject.QuestAttributes }


createQuest :
    CreateQuestRequiredArguments
    -> SelectionSet decodesTo Api.Object.QuestResult
    -> SelectionSet (Maybe decodesTo) RootMutation
createQuest requiredArgs____ object____ =
    Object.selectionForCompositeField "createQuest" [ Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeQuestAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias CreateQuestObjectiveRequiredArguments =
    { attributes : Api.InputObject.QuestObjectiveAttributes }


createQuestObjective :
    CreateQuestObjectiveRequiredArguments
    -> SelectionSet decodesTo Api.Object.QuestObjectiveResult
    -> SelectionSet (Maybe decodesTo) RootMutation
createQuestObjective requiredArgs____ object____ =
    Object.selectionForCompositeField "createQuestObjective" [ Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeQuestObjectiveAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias CreateQuestRewardRequiredArguments =
    { attributes : Api.InputObject.QuestRewardAttributes }


createQuestReward :
    CreateQuestRewardRequiredArguments
    -> SelectionSet decodesTo Api.Object.QuestRewardResult
    -> SelectionSet (Maybe decodesTo) RootMutation
createQuestReward requiredArgs____ object____ =
    Object.selectionForCompositeField "createQuestReward" [ Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeQuestRewardAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias CreateResourceRequiredArguments =
    { attributes : Api.InputObject.ResourceAttributes }


createResource :
    CreateResourceRequiredArguments
    -> SelectionSet decodesTo Api.Object.ResourceResult
    -> SelectionSet (Maybe decodesTo) RootMutation
createResource requiredArgs____ object____ =
    Object.selectionForCompositeField "createResource" [ Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeResourceAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias CreateZoneRequiredArguments =
    { attributes : Api.InputObject.ZoneAttributes }


createZone :
    CreateZoneRequiredArguments
    -> SelectionSet decodesTo Api.Object.ZoneResult
    -> SelectionSet (Maybe decodesTo) RootMutation
createZone requiredArgs____ object____ =
    Object.selectionForCompositeField "createZone" [ Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeZoneAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteItemRequiredArguments =
    { id : Api.ScalarCodecs.Id }


deleteItem :
    DeleteItemRequiredArguments
    -> SelectionSet decodesTo Api.Object.ItemResult
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteItem requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteItem" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteMonsterRequiredArguments =
    { id : Api.ScalarCodecs.Id }


deleteMonster :
    DeleteMonsterRequiredArguments
    -> SelectionSet decodesTo Api.Object.MonsterResult
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteMonster requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteMonster" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteNpcRequiredArguments =
    { id : Api.ScalarCodecs.Id }


deleteNpc :
    DeleteNpcRequiredArguments
    -> SelectionSet decodesTo Api.Object.NpcResult
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteNpc requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteNpc" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias RemoveDroppedItemFromMonsterRequiredArguments =
    { monsterId : Api.ScalarCodecs.Id
    , itemId : Api.ScalarCodecs.Id
    }


{-| Remove an item from a monster's drop table.
This never fails, removing an item that was not present is a no-op and will return success true.

  - monsterId - ID of Monster to remove from
  - itemId - Item ID to remove

-}
removeDroppedItemFromMonster :
    RemoveDroppedItemFromMonsterRequiredArguments
    -> SelectionSet decodesTo Api.Object.SuccessResult
    -> SelectionSet (Maybe decodesTo) RootMutation
removeDroppedItemFromMonster requiredArgs____ object____ =
    Object.selectionForCompositeField "removeDroppedItemFromMonster" [ Argument.required "monsterId" requiredArgs____.monsterId (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "itemId" requiredArgs____.itemId (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias RemoveSoldItemFromNpcRequiredArguments =
    { npcId : Api.ScalarCodecs.Id
    , itemId : Api.ScalarCodecs.Id
    }


{-| Remove an item from an NPC's vendor sell list.
This never fails, removing an item that was not present is a no-op and will return success true.

  - npcId - ID of NPC to remove from
  - itemId - Item ID to remove

-}
removeSoldItemFromNpc :
    RemoveSoldItemFromNpcRequiredArguments
    -> SelectionSet decodesTo Api.Object.SuccessResult
    -> SelectionSet (Maybe decodesTo) RootMutation
removeSoldItemFromNpc requiredArgs____ object____ =
    Object.selectionForCompositeField "removeSoldItemFromNpc" [ Argument.required "npcId" requiredArgs____.npcId (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "itemId" requiredArgs____.itemId (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateItemRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , attributes : Api.InputObject.ItemAttributes
    }


updateItem :
    UpdateItemRequiredArguments
    -> SelectionSet decodesTo Api.Object.ItemResult
    -> SelectionSet (Maybe decodesTo) RootMutation
updateItem requiredArgs____ object____ =
    Object.selectionForCompositeField "updateItem" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeItemAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateMonsterRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , attributes : Api.InputObject.MonsterAttributes
    }


updateMonster :
    UpdateMonsterRequiredArguments
    -> SelectionSet decodesTo Api.Object.MonsterResult
    -> SelectionSet (Maybe decodesTo) RootMutation
updateMonster requiredArgs____ object____ =
    Object.selectionForCompositeField "updateMonster" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeMonsterAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateNpcRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , attributes : Api.InputObject.NpcAttributes
    }


updateNpc :
    UpdateNpcRequiredArguments
    -> SelectionSet decodesTo Api.Object.NpcResult
    -> SelectionSet (Maybe decodesTo) RootMutation
updateNpc requiredArgs____ object____ =
    Object.selectionForCompositeField "updateNpc" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeNpcAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateQuestRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , attributes : Api.InputObject.QuestAttributes
    }


updateQuest :
    UpdateQuestRequiredArguments
    -> SelectionSet decodesTo Api.Object.QuestResult
    -> SelectionSet (Maybe decodesTo) RootMutation
updateQuest requiredArgs____ object____ =
    Object.selectionForCompositeField "updateQuest" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeQuestAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateQuestObjectiveRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , attributes : Api.InputObject.QuestObjectiveAttributes
    }


updateQuestObjective :
    UpdateQuestObjectiveRequiredArguments
    -> SelectionSet decodesTo Api.Object.QuestResult
    -> SelectionSet (Maybe decodesTo) RootMutation
updateQuestObjective requiredArgs____ object____ =
    Object.selectionForCompositeField "updateQuestObjective" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeQuestObjectiveAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateQuestRewardRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , attributes : Api.InputObject.QuestRewardAttributes
    }


updateQuestReward :
    UpdateQuestRewardRequiredArguments
    -> SelectionSet decodesTo Api.Object.QuestResult
    -> SelectionSet (Maybe decodesTo) RootMutation
updateQuestReward requiredArgs____ object____ =
    Object.selectionForCompositeField "updateQuestReward" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeQuestRewardAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateResourceRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , attributes : Api.InputObject.ResourceAttributes
    }


updateResource :
    UpdateResourceRequiredArguments
    -> SelectionSet decodesTo Api.Object.ResourceResult
    -> SelectionSet (Maybe decodesTo) RootMutation
updateResource requiredArgs____ object____ =
    Object.selectionForCompositeField "updateResource" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeResourceAttributes ] object____ (Basics.identity >> Decode.nullable)


type alias UpdateZoneRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , attributes : Api.InputObject.ZoneAttributes
    }


updateZone :
    UpdateZoneRequiredArguments
    -> SelectionSet decodesTo Api.Object.ZoneResult
    -> SelectionSet (Maybe decodesTo) RootMutation
updateZone requiredArgs____ object____ =
    Object.selectionForCompositeField "updateZone" [ Argument.required "id" requiredArgs____.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "attributes" requiredArgs____.attributes Api.InputObject.encodeZoneAttributes ] object____ (Basics.identity >> Decode.nullable)
