-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Item
    = Item


type ItemResult
    = ItemResult


type ItemStats
    = ItemStats


type Location
    = Location


type Monster
    = Monster


type MonsterResult
    = MonsterResult


type Npc
    = Npc


type NpcResult
    = NpcResult


type Patch
    = Patch


type Quest
    = Quest


type QuestObjective
    = QuestObjective


type QuestObjectiveResult
    = QuestObjectiveResult


type QuestResult
    = QuestResult


type QuestReward
    = QuestReward


type QuestRewardResult
    = QuestRewardResult


type Resource
    = Resource


type ResourceResult
    = ResourceResult


type SuccessResult
    = SuccessResult


type Zone
    = Zone


type ZoneResult
    = ZoneResult
