-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias ISO8601DateTime =
    Api.Scalar.ISO8601DateTime


type alias Id =
    Api.Scalar.Id


codecs : Api.Scalar.Codecs ISO8601DateTime Id
codecs =
    Api.Scalar.defineCodecs
        { codecISO8601DateTime = defaultCodecs.codecISO8601DateTime
        , codecId = defaultCodecs.codecId
        }
