-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PantheonApi.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import PantheonApi.Scalar exposing (defaultCodecs)


type alias ISO8601DateTime =
    PantheonApi.Scalar.ISO8601DateTime


type alias Id =
    PantheonApi.Scalar.Id


codecs : PantheonApi.Scalar.Codecs ISO8601DateTime Id
codecs =
    PantheonApi.Scalar.defineCodecs
        { codecISO8601DateTime = defaultCodecs.codecISO8601DateTime
        , codecId = defaultCodecs.codecId
        }
