-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Location exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


createdAt : SelectionSet Api.ScalarCodecs.ISO8601DateTime Api.Object.Location
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


dungeon :
    SelectionSet decodesTo Api.Object.Dungeon
    -> SelectionSet (Maybe decodesTo) Api.Object.Location
dungeon object____ =
    Object.selectionForCompositeField "dungeon" [] object____ (Basics.identity >> Decode.nullable)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Location
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


monsters :
    SelectionSet decodesTo Api.Object.Monster
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.Location
monsters object____ =
    Object.selectionForCompositeField "monsters" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


name : SelectionSet String Api.Object.Location
name =
    Object.selectionForField "String" "name" [] Decode.string


npcs :
    SelectionSet decodesTo Api.Object.Npc
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.Location
npcs object____ =
    Object.selectionForCompositeField "npcs" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


settlement :
    SelectionSet decodesTo Api.Object.Settlement
    -> SelectionSet (Maybe decodesTo) Api.Object.Location
settlement object____ =
    Object.selectionForCompositeField "settlement" [] object____ (Basics.identity >> Decode.nullable)


updatedAt : SelectionSet Api.ScalarCodecs.ISO8601DateTime Api.Object.Location
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


zone :
    SelectionSet decodesTo Api.Object.Zone
    -> SelectionSet decodesTo Api.Object.Location
zone object____ =
    Object.selectionForCompositeField "zone" [] object____ Basics.identity
