-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Npc exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


createdAt : SelectionSet Api.ScalarCodecs.ISO8601DateTime Api.Object.Npc
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Npc
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


locX : SelectionSet (Maybe Float) Api.Object.Npc
locX =
    Object.selectionForField "(Maybe Float)" "locX" [] (Decode.float |> Decode.nullable)


locY : SelectionSet (Maybe Float) Api.Object.Npc
locY =
    Object.selectionForField "(Maybe Float)" "locY" [] (Decode.float |> Decode.nullable)


locZ : SelectionSet (Maybe Float) Api.Object.Npc
locZ =
    Object.selectionForField "(Maybe Float)" "locZ" [] (Decode.float |> Decode.nullable)


location :
    SelectionSet decodesTo Api.Object.Location
    -> SelectionSet decodesTo Api.Object.Npc
location object____ =
    Object.selectionForCompositeField "location" [] object____ Basics.identity


name : SelectionSet String Api.Object.Npc
name =
    Object.selectionForField "String" "name" [] Decode.string


patch :
    SelectionSet decodesTo Api.Object.Patch
    -> SelectionSet decodesTo Api.Object.Npc
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


questsGiven :
    SelectionSet decodesTo Api.Object.Quest
    -> SelectionSet (List decodesTo) Api.Object.Npc
questsGiven object____ =
    Object.selectionForCompositeField "questsGiven" [] object____ (Basics.identity >> Decode.list)


questsReceived :
    SelectionSet decodesTo Api.Object.Quest
    -> SelectionSet (List decodesTo) Api.Object.Npc
questsReceived object____ =
    Object.selectionForCompositeField "questsReceived" [] object____ (Basics.identity >> Decode.list)


sellsItems :
    SelectionSet decodesTo Api.Object.Item
    -> SelectionSet (List decodesTo) Api.Object.Npc
sellsItems object____ =
    Object.selectionForCompositeField "sellsItems" [] object____ (Basics.identity >> Decode.list)


subtitle : SelectionSet (Maybe String) Api.Object.Npc
subtitle =
    Object.selectionForField "(Maybe String)" "subtitle" [] (Decode.string |> Decode.nullable)


updatedAt : SelectionSet Api.ScalarCodecs.ISO8601DateTime Api.Object.Npc
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


vendor : SelectionSet Bool Api.Object.Npc
vendor =
    Object.selectionForField "Bool" "vendor" [] Decode.bool


{-| Shortcut for location -> zone. May be removed.
-}
zone :
    SelectionSet decodesTo Api.Object.Zone
    -> SelectionSet decodesTo Api.Object.Npc
zone object____ =
    Object.selectionForCompositeField "zone" [] object____ Basics.identity
