-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Quest exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


createdAt : SelectionSet Api.ScalarCodecs.ISO8601DateTime Api.Object.Quest
createdAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)


{-| Item that starts this Quest
-}
droppedAs :
    SelectionSet decodesTo Api.Object.Item
    -> SelectionSet (Maybe decodesTo) Api.Object.Quest
droppedAs object____ =
    Object.selectionForCompositeField "droppedAs" [] object____ (Basics.identity >> Decode.nullable)


{-| Npc that starts this Quest
-}
giver :
    SelectionSet decodesTo Api.Object.Npc
    -> SelectionSet (Maybe decodesTo) Api.Object.Quest
giver object____ =
    Object.selectionForCompositeField "giver" [] object____ (Basics.identity >> Decode.nullable)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Quest
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String Api.Object.Quest
name =
    Object.selectionForField "String" "name" [] Decode.string


patch :
    SelectionSet decodesTo Api.Object.Patch
    -> SelectionSet decodesTo Api.Object.Quest
patch object____ =
    Object.selectionForCompositeField "patch" [] object____ Basics.identity


{-| Quest that must be complete before this one is available
-}
prereqQuest :
    SelectionSet decodesTo Api.Object.Quest
    -> SelectionSet (Maybe decodesTo) Api.Object.Quest
prereqQuest object____ =
    Object.selectionForCompositeField "prereqQuest" [] object____ (Basics.identity >> Decode.nullable)


questObjectives :
    SelectionSet decodesTo Api.Object.QuestObjective
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.Quest
questObjectives object____ =
    Object.selectionForCompositeField "questObjectives" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


questRewards :
    SelectionSet decodesTo Api.Object.QuestReward
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.Quest
questRewards object____ =
    Object.selectionForCompositeField "questRewards" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| Npc that completes this Quest
-}
receiver :
    SelectionSet decodesTo Api.Object.Npc
    -> SelectionSet (Maybe decodesTo) Api.Object.Quest
receiver object____ =
    Object.selectionForCompositeField "receiver" [] object____ (Basics.identity >> Decode.nullable)


{-| Quests that open after this one is complete
-}
successiveQuests :
    SelectionSet decodesTo Api.Object.Quest
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.Quest
successiveQuests object____ =
    Object.selectionForCompositeField "successiveQuests" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


text : SelectionSet String Api.Object.Quest
text =
    Object.selectionForField "String" "text" [] Decode.string


updatedAt : SelectionSet Api.ScalarCodecs.ISO8601DateTime Api.Object.Quest
updatedAt =
    Object.selectionForField "ScalarCodecs.ISO8601DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecISO8601DateTime |> .decoder)
